#!/bin/bash

command -v tree >/dev/null 2>&1 || {
    echo "tree Command Was Not Found. Not Updating README."
    exit 1
}

# Update the README with new file structure.
cat ./.readme_gen/README_TITLE.md > README.md
echo "\`\`\`" >> temp.txt # Start markdown code block
tree >> temp.txt
echo "\`\`\`" >> temp.txt # End markdown code block

awk '{print $0"  "}' temp.txt >> README.md
rm temp.txt
echo "README was updated."

git add README.md
